// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Ganti semua nilai di bawah ini dengan nilai dari project Firebase Anda.
  // Jalankan: dart run flutterfire_cli:flutterfire configure
  // File ini akan di-overwrite otomatis.

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1CKTWr0CeqiGYdwDuAfV6CTKgcOJP_YI',
    appId: '1:407133248879:web:68cc5755d13d13545c9c9a',
    messagingSenderId: '407133248879',
    projectId: 'aplikasispiltbill',
    authDomain: 'aplikasispiltbill.firebaseapp.com',
    storageBucket: 'aplikasispiltbill.firebasestorage.app',
    measurementId: 'G-WKLC4Z56KE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzwXDb7X8qsQk_ynZl5e4ONiNvuwH9pDw',
    appId: '1:407133248879:android:0653b4437aede4605c9c9a',
    messagingSenderId: '407133248879',
    projectId: 'aplikasispiltbill',
    storageBucket: 'aplikasispiltbill.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.aplikasispiltbillUas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.aplikasispiltbillUas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1CKTWr0CeqiGYdwDuAfV6CTKgcOJP_YI',
    appId: '1:407133248879:web:e71ffad6f50abca45c9c9a',
    messagingSenderId: '407133248879',
    projectId: 'aplikasispiltbill',
    authDomain: 'aplikasispiltbill.firebaseapp.com',
    storageBucket: 'aplikasispiltbill.firebasestorage.app',
    measurementId: 'G-1JPPXT5BQ9',
  );
}
